### ISSUE TITLE
A simple bug in layout.c: center alignment is not correct

### ISSUE THREAD

**Issue by shanshe** [adkennan/DockBot#1]
First of all, thanks for sharing this program, I use it on all my Amigas!!! I have detected a simple bug in layout.c line 206:
l = (screen->Width + width) / 2;

should be

l = (screen->Width - width) / 2;

Thank you for supporting Amiga computers and amigans :)

**Comment by adkennan** [comment]
Hi shanshe, thanks for reporting this bug (and for using DockBot!). Clearly I haven't used a horizontally centred window.

I'll see if I can get a fix out in the next few days.

Andrew

**Comment by adkennan** [comment]
Fixed in v1.2 :)
