### ISSUE TITLE
DockBot won't start :(

### ISSUE THREAD

**Issue by Andiweli** [adkennan/DockBot#2]
I wanted to try this Dock instead of AmiDock.
Installed it but it won't boot when starting - also manual starting the app doesn't work.
Trying to open the Prefs editor results in an error "No config found" - and it quits.

Any idea?
Amiga OS 3.9 with 68040 and Picasso here.

**Comment by adkennan** [comment]
Thanks for getting in touch. Did you install it using the Install script? 

The installer should have copied a config file called DockBot.prefs into ENV: and ENVARC:. If it isn't there you should be able to manually copy it.

**Comment by Andiweli** [comment]
Hi there!
Double checked now - the .prefs file is there - in ENV: and ENVARC:
But DockBot won't start and the Prefs tool still tells me problems with the config and quits.

**Comment by adkennan** [comment]
The default DockBot.prefs file is in the archive. Can you try manually copying that to ENV: ?
